# Generated by Django 2.2 on 2019-04-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key='true', serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('emailid', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('PRN', models.CharField(max_length=15)),
            ],
        ),
    ]
