# Generated by Django 2.2 on 2019-04-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rates',
            fields=[
                ('city', models.CharField(max_length=15, primary_key='true', serialize=False)),
                ('Ahmedabad', models.CharField(max_length=15)),
                ('Nadiad', models.CharField(max_length=15)),
                ('Anand', models.CharField(max_length=15)),
                ('Vadodara', models.CharField(max_length=15)),
                ('Bharuch', models.CharField(max_length=15)),
                ('Surat', models.CharField(max_length=15)),
                ('Navsari', models.CharField(max_length=15)),
                ('Valsad', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Trainlist',
            fields=[
                ('tid', models.CharField(max_length=10, primary_key='true', serialize=False)),
                ('tname', models.CharField(max_length=100)),
            ],
        ),
    ]
