# Generated by Django 2.2 on 2019-04-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0005_auto_20190411_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ticket_details',
            new_name='ticketdetails',
        ),
        migrations.RenameField(
            model_name='ticketdetails',
            old_name='trainnm',
            new_name='tnm',
        ),
    ]
