# Generated by Django 2.1.7 on 2019-04-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0007_ticketdetails_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='cost',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station', models.CharField(max_length=15)),
                ('cost', models.CharField(max_length=10)),
            ],
        ),
    ]
