# Generated by Django 2.1.7 on 2019-04-11 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0008_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='cost',
            new_name='costy',
        ),
    ]
